-- DDL

CREATE DATABASE ProVagas

GO

USE ProVagas

GO

CREATE TABLE TipoUsuario (
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	NomeTipoUsuario VARCHAR (255) NOT NULL 
)

GO

CREATE TABLE Genero (
	IdGenero INT PRIMARY KEY IDENTITY,
	NomeGenero VARCHAR (255) NOT NULL
)

GO

CREATE TABLE Estado (
	IdEstado INT PRIMARY KEY IDENTITY,
	NomeEstado VARCHAR (255) NOT NULL
)

GO

CREATE TABLE  Cidade (
	IdCidade INT PRIMARY KEY IDENTITY,
	NomeCidade VARCHAR (255) NOT NULL,
	IdEstado INT FOREIGN KEY REFERENCES Estado(IdEstado)
)

GO

CREATE TABLE Endereco (
	IdEndereco INT PRIMARY KEY IDENTITY,
	Telefone VARCHAR (20),
	Rua VARCHAR (255) NOT NULL,
	Num VARCHAR (10) NOT NULL,
	Bairro VARCHAR (100) NOT NULL,
	Complemento VARCHAR (20),
	CEP CHAR(8) NOT NULL,
	IdCidade INT FOREIGN KEY REFERENCES Cidade(IdCIdade) NOT NULL,
)

GO

CREATE TABLE Usuario (
	IdUsuario INT PRIMARY KEY IDENTITY,
	Email VARCHAR (255) NOT NULL UNIQUE,
	Senha VARCHAR (64) NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTIpoUsuario)NOT NULL,
	IdEndereco INT FOREIGN KEY REFERENCES Endereco(IdEndereco) NOT NULL
)

GO

CREATE TABLE NivelEscolaridade (
	IdNivelEscolaridade INT PRIMARY KEY IDENTITY,
	Escolaridade VARCHAR
)

GO

CREATE TABLE NivelIngles (
	IdNivelIngles INT PRIMARY KEY IDENTITY,
	Ingles VARCHAR
)

GO

CREATE TABLE Candidato (
	IdCandidato INT PRIMARY KEY IDENTITY,
	NomeCompletoCandidato VARCHAR (255) NOT NULL,
	CPF CHAR (11) UNIQUE,
	DataNascimento DATE NOT NULL,
	Linkedin VARCHAR (200),
	FotoPerfil IMAGE,
	PossuiDeficiencia BIT NOT NULL,
	Deficiencia VARCHAR (255),
	CursandoSENAI BIT NOT NULL,
	Curso VARCHAR(255),
	Habilidades VARCHAR (255) NOT NULL,
	NomeEmpresaExperienciaProfissional VARCHAR (50),
	Cargo VARCHAR (50),
	EmpregoAtual BIT,
	Atividades VARCHAR (255),
	IdUsuario INT FOREIGN KEY REFERENCES Usuario (IdUsuario) NOT NULL,
	IdGenero INT FOREIGN KEY REFERENCES Genero (IdGenero) NOT NULL,
	IdNivelIngles INT FOREIGN KEY REFERENCES NivelIngles (IdNivelIngles) NOT NULL,
	IdNivelEscolaridade INT FOREIGN KEY REFERENCES NivelEscolaridade (IdNivelEscolaridade) NOT NULL
)

GO

CREATE TABLE Administrador (
	IdAdministrador INT PRIMARY KEY IDENTITY,
	NomeCompletoAdmin VARCHAR (255) NOT NULL,
	NIF CHAR(9) UNIQUE,
	UnidadeSENAI VARCHAR (255) NOT NULL,
	Departamento VARCHAR (255) NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
)

GO

CREATE TABLE Empresa (
	IdEmpresa INT PRIMARY KEY IDENTITY,
	RazaoSocial VARCHAR (255) NOT NULL,
	NomeFantasia VARCHAR (255) NOT NULL,
	PorteEmpresa VARCHAR (255) NOT NULL,
	NomeParaContato VARCHAR (255) NOT NULL,
	Linkedin VARCHAR (255),
	Website VARCHAR (255),
	CNPJ CHAR (14) NOT NULL UNIQUE,
	CNAE CHAR (7) NOT NULL UNIQUE,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL
)

GO

CREATE TABLE TipoVaga (
	IdTipoVaga INT PRIMARY KEY IDENTITY,
	NomeTipoVaga VARCHAR (255) NOT NULL
)

GO

CREATE TABLE Vaga (
	IdVaga INT PRIMARY KEY IDENTITY,
	NomeVaga VARCHAR (255) NOT NULL,
	DescricaoAtividade VARCHAR (255) NOT NULL,
	DescricaoRequisito VARCHAR (255) NOT NULL,
	DataInicio DATETIME NOT NULL,
	DataFinal DATETIME NOT NULL,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa (IdEmpresa) NOT NULL,
	IdTipoVaga INT FOREIGN KEY REFERENCES TipoVaga(IdTipoVaga) NOT NULL
)

GO

CREATE TABLE StatusInscricao (
	IdStatusInscricao INT PRIMARY KEY IDENTITY,
	NomeStatus VARCHAR (255) NOT NULL
)

CREATE TABLE Inscricao (
	IdInscricao INT PRIMARY KEY IDENTITY,
	DataInscricao DATE NOT NULL,
	IdVaga INT FOREIGN KEY REFERENCES Vaga(IdVaga) NOT NULL,
	IdStatusInscricao INT FOREIGN KEY REFERENCES StatusInscricao(IdStatusInscricao) NOT NULL,
	IdCandidato INT FOREIGN KEY REFERENCES Candidato(IdCandidato) NOT NULL
)

GO

CREATE TABLE StatusEstagio (
	IdStatusEstagio INT PRIMARY KEY IDENTITY,
	NomeStatus VARCHAR (255) NOT NULL
)

GO

CREATE TABLE Estagio (
	IdEstagio INT PRIMARY KEY IDENTITY,
	DataInicio DATE NOT NULL,
	DataFinal DATE NOT NULL,
	IdInscricao INT FOREIGN KEY REFERENCES Inscricao (IdInscricao),
	IdStatusEstagio INT FOREIGN KEY REFERENCES StatusEstagio (IdStatusEstagio)
)

GO

CREATE TABLE Beneficio (
	IdBeneficio INT PRIMARY KEY IDENTITY,
	NomeBeneficio VARCHAR (255) NOT NULL
)

GO

CREATE TABLE BeneficioXVaga (
	IdBeneficioVaga INT PRIMARY KEY IDENTITY,
	IdBeneficio INT FOREIGN KEY REFERENCES Beneficio (IdBeneficio) NOT NULL,
	IdVaga INT FOREIGN KEY REFERENCES Vaga (IdVaga) NOT NULL
)

