-- DDL

CREATE DATABASE ProVagas

GO

USE ProVagas

GO

CREATE TABLE TipoUsuario (
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	NomeTipoUsuario VARCHAR (255) NOT NULL 
)

GO

CREATE TABLE Genero (
	IdGenero INT PRIMARY KEY IDENTITY,
	NomeGenero VARCHAR (255) NOT NULL
)

GO

CREATE TABLE Estado (
	IdEstado INT PRIMARY KEY IDENTITY,
	NomeEstado VARCHAR (255) NOT NULL
)

GO

CREATE TABLE  Cidade (
	IdCidade INT PRIMARY KEY IDENTITY,
	NomeCidade VARCHAR (255) NOT NULL,
	IdEstado INT FOREIGN KEY REFERENCES Estado(IdEstado)
)

GO

CREATE TABLE Usuario (
	IdUsuario INT PRIMARY KEY IDENTITY,
	Email VARCHAR (255) NOT NULL UNIQUE,
	Senha VARCHAR (64) NOT NULL,
	Telefone VARCHAR (20) NOT NULL UNIQUE,
	Rua VARCHAR (255) NOT NULL,
	Num VARCHAR (10) NOT NULL,
	Bairro VARCHAR (100) NOT NULL,
	Complemento VARCHAR (20),
	CEP CHAR(8),
	IdCidade INT FOREIGN KEY REFERENCES Cidade(IdCIdade) NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTIpoUsuario) NOT NULL,
)

GO

CREATE TABLE Candidato (
	IdCandidato INT PRIMARY KEY IDENTITY,
	NomeCompletoCandidato VARCHAR (255) NOT NULL,
	CPF CHAR (11) NOT NULL UNIQUE,
	DataNascimento DATE NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario (IdUsuario) NOT NULL,
	IdGenero INT FOREIGN KEY REFERENCES Genero (IdGenero) NOT NULL
)

GO

CREATE TABLE Administrador (
	IdAdministrador INT PRIMARY KEY IDENTITY,
	NomeCompletoAdmin VARCHAR (255) NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	NIF CHAR(9) UNIQUE
)

GO

CREATE TABLE Empresa (
	IdEmpresa INT PRIMARY KEY IDENTITY,
	RazaoSocial VARCHAR (255) NOT NULL,
	NomeFantasia VARCHAR (255) NOT NULL,
	Porte VARCHAR (255) NOT NULL,
	CNPJ CHAR (14) NOT NULL UNIQUE,
	CNAE CHAR (7) NOT NULL UNIQUE,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL
)

GO

CREATE TABLE TipoVaga (
	IdTipoVaga INT PRIMARY KEY IDENTITY,
	NomeTipoVaga VARCHAR (255) NOT NULL
)

GO

CREATE TABLE Vaga (
	IdVaga INT PRIMARY KEY IDENTITY,
	NomeVaga VARCHAR (255) NOT NULL,
	DescricaoAtividade VARCHAR (255) NOT NULL,
	DescricaoRequisito VARCHAR (255) NOT NULL,
	DataInicio DATETIME NOT NULL,
	DataFinal DATETIME NOT NULL,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa (IdEmpresa) NOT NULL,
	IdTipoVaga INT FOREIGN KEY REFERENCES TipoVaga(IdTipoVaga) NOT NULL
)

CREATE TABLE StatusInscricao (
	IdStatusInscricao INT PRIMARY KEY IDENTITY,
	NomeStatus VARCHAR (255) NOT NULL
)

CREATE TABLE Inscricao (
	IdInscricao INT PRIMARY KEY IDENTITY,
	IdVaga INT FOREIGN KEY REFERENCES Vaga(IdVaga) NOT NULL,
	IdStatusInscricao INT FOREIGN KEY REFERENCES StatusInscricao(IdStatusInscricao) NOT NULL,
	IdCandidato INT FOREIGN KEY REFERENCES Candidato(IdCandidato) NOT NULL
)

CREATE TABLE Estagio (
	IdEstagio INT PRIMARY KEY IDENTITY,
	Datainicio DATE NOT NULL,
	DataFim DATE NOT NULL,
	IdCandidato INT FOREIGN KEY REFERENCES Candidato (IdCandidato) NOT NULL,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa (IdEmpresa) NOT NULL
)

CREATE TABLE Beneficio (
	IdBeneficio INT PRIMARY KEY IDENTITY,
	NomeBeneficio VARCHAR (255) NOT NULL
)

CREATE TABLE BeneficioXVaga (
	IdBeneficioVaga INT PRIMARY KEY IDENTITY,
	IdBeneficio INT FOREIGN KEY REFERENCES Beneficio (IdBeneficio) NOT NULL,
	IdVaga INT FOREIGN KEY REFERENCES Vaga (IdVaga) NOT NULL
)

